AllCops:
  TargetRubyVersion: 2.3.0
  Exclude:
    - 'lib/asciidoctor/inline_parser/asciidoctor*grammar.rb'

Metrics/LineLength:
  Max: 120
  Exclude:
    - 'test/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses

Style/SafeNavigation:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'test/*'

Metrics/ModuleLength:
  Max: 200

Metrics/MethodLength:
  Max: 20
